version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=testapp
      - MYSQL_ROOT_PASSWORD=test1234
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    depends_on:
      - db
    build:
      context: backend-test-app/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  frontend:
    depends_on:
      - backend
    build:
      context: frontend-test-app/
      dockerfile: Dockerfile
    ports:
      - '80:80'